version: '3.8'

services: 
  database:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  app:
    build: ./src
    env_file: 
      - .env
    depends_on:
      - database
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
  pgadmin: